FROM node:23-alpine3.20

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
#COPY .npmrc ./
COPY src ./src
COPY tools ./tools

ARG NPM_TOKEN
# Create .npmrc with the token and registry configuration
RUN echo "@abdulrehman1363:registry=https://npm.pkg.github.com/" > .npmrc && \
    echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc

RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 4001
CMD [ "npm", "run", "dev" ]
